GET http://localhost:5000/


###
POST https://lms-il7o.onrender.com/api/users
Content-Type: application/json

{
  "id": "user_12346",
    "email_addresses": [
      {
        "email_address": "test@example.com"
      }
    ],
    "first_name": "Emma",
    "last_name": "Stone",
    "image_Url": "https://example.com/image.png"
}