GET http://localhost:5000/


###
POST https://lms-il7o.onrender.com/api/users
Content-Type: application/json

{
  "id": "user_12",
    "email_addresses": [
      {
        "email_address": "test@example.com"
      }
    ],
    "first_name": "Emma",
    "last_name": "Stone",
    "image_Url": "https://example.com/image.png"
}
###
POST http://localhost:5000/api/signup
Content-Type: application/json

{"username": "alem", "password": "alemalem", "email": "won.babg@gmail.com"}
###
POST http://localhost:5000/api/login
Content-Type: application/json

{"username": "alem", "password": "alemalem"}

###
POST http://localhost:5000/api/logout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsdWxhNTYiLCJpZCI6IjY4NTVhNjViNzljNmZkNGQwZjliMWM4MyIsImlhdCI6MTc1MDQ0MzYxMSwiZXhwIjoxNzUwNTMwMDExfQ.utPCLpYS3lZgFCbFXDow5M2Pcp93EpfZ8xfGFIxjCU0; Max-Age=604800; Path=/; Expires=Fri, 27 Jun 2025 18:20:11 GMT; HttpOnly; SameSite=Lax


###
POST http://localhost:5000/api/me
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsdWxhNTYiLCJpZCI6IjY4NTVhNjViNzljNmZkNGQwZjliMWM4MyIsImlhdCI6MTc1MDQ0MzYxMSwiZXhwIjoxNzUwNTMwMDExfQ.utPCLpYS3lZgFCbFXDow5M2Pcp93EpfZ8xfGFIxjCU0; Max-Age=604800; Path=/; Expires=Fri, 27 Jun 2025 18:20:11 GMT; HttpOnly; SameSite=Lax

###
POST http://localhost:5000/api/forgot-password
Content-Type: application/json


{"resetEmail": "won.babg@gmail.com"}


###
POST http://localhost:5000/api/educator/add-course
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZW0iLCJpZCI6IjY4NWZjYzk2YmYzYjYzMzE0ZmNlYjkxZiIsInJvbGUiOiJlZHVjYXRvciIsImlhdCI6MTc1MTEwODg2NywiZXhwIjoxNzUxMTk1MjY3fQ.4hK_pH3JLej46YoLPy0cyo0y_W5M5cbmQa3idhHm9FA; Max-Age=604800; Path=/; Expires=Sat, 05 Jul 2025 11:07:47 GMT; HttpOnly; Secure; SameSite=None
Content-Type: application/json

 {"courseData": 
      {
            "courseTitle": "Introduction to JavaScript",
            "courseDescription": "Learn the Basics of JavaScriptAsafSDFASDFS",
            "coursePrice": 49.99,
            "isPublished": true,
            "discount": 20,
            "courseContent": [
                {
                    "chapterId": "chapter1", 
                    "chapterOrder": 1,
                    "chapterTitle": "Getting Started with JavaScript",
                    "chapterContent": [
                        {
                            "lectureId": "lecture1",
                            "lectureTitle": "What is JavaScript?",
                            "lectureDuration": 16,
                            "lectureUrl": "https://youtu.be/CBWnBi-awSA",
                            "isPreviewFree": true,
                            "lectureOrder": 1
                        }
                    ]
                },
                {   
                    "chapterId": "chapter2", 
                    "chapterOrder": 2,
                    "chapterTitle": "Variables and Data Types",
                    "chapterContent": [
                        {
                            "lectureId": "lecture2",
                            "lectureTitle": "Understanding Variables",
                            "lectureDuration": 20,
                            "lectureUrl": "https://youtu.be/pZQeBJsGoDQ",
                            "isPreviewFree": true,
                            "lectureOrder": 1
                        },
                        {
                            "lectureId": "lecture3",
                            "lectureTitle": "Data Types in JavaScript",
                            "lectureDuration": 10,
                            "lectureUrl": "https://youtu.be/ufHT2WEkkC4",
                            "isPreviewFree": false,
                            "lectureOrder": 2
                        }
                    ]
                }
            ],
            "educator": "675ac1512100b91a6d9b8b24",
            "enrolledStudents": [
                "user_2qQlvXyr02B4Bq6hT0Gvaa5fT9V",
                "user_2qQlvXyr02B4Bq6hT0Gvaa5fT9V",
                "user_2qjlgkAqIMpiR2flWIRzvWKtE0w"
            ],
            "courseRatings": [
                {
                    "userId": "user_2qjlgkAqIMpiR2flWIRzvWKtE0w",
                    "rating": 4
                }
            ],
      
            "courseThumbnail": "https://img.youtube.com/vi/CBWnBi-awSA/maxresdefault.jpg"
        }
    }
###
GET http://localhost:5000/api/educator/courses
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZW0iLCJpZCI6IjY4NWZjYzk2YmYzYjYzMzE0ZmNlYjkxZiIsInJvbGUiOiJlZHVjYXRvciIsImlhdCI6MTc1MTEwODg2NywiZXhwIjoxNzUxMTk1MjY3fQ.4hK_pH3JLej46YoLPy0cyo0y_W5M5cbmQa3idhHm9FA; Max-Age=604800; Path=/; Expires=Sat, 05 Jul 2025 11:07:47 GMT; HttpOnly; Secure; SameSite=None

###
GET http://localhost:5000/api/course/all

###
GET http://localhost:5000/api/course/685fdf323cdad59462ff93d2


###
GET http://localhost:5000/api/user/data
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZW0iLCJpZCI6IjY4NWZjYzk2YmYzYjYzMzE0ZmNlYjkxZiIsInJvbGUiOiJlZHVjYXRvciIsImlhdCI6MTc1MTEyNjA3MSwiZXhwIjoxNzUxMjEyNDcxfQ.7lL7Tw3LPLhnVBOj6zIBbliaD2rB-GE1-YVWZ2khXL8; Max-Age=604800; Path=/; Expires=Sat, 05 Jul 2025 15:54:31 GMT; HttpOnly; Secure; SameSite=None

###
GET http://localhost:5000/api/user/enrolled-courses
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZW0iLCJpZCI6IjY4NWZjYzk2YmYzYjYzMzE0ZmNlYjkxZiIsInJvbGUiOiJlZHVjYXRvciIsImlhdCI6MTc1MTEyNjA3MSwiZXhwIjoxNzUxMjEyNDcxfQ.7lL7Tw3LPLhnVBOj6zIBbliaD2rB-GE1-YVWZ2khXL8; Max-Age=604800; Path=/; Expires=Sat, 05 Jul 2025 15:54:31 GMT; HttpOnly; Secure; SameSite=None

###
POST  http://localhost:5000/api/user/purchase
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZW0iLCJpZCI6IjY4NWZjYzk2YmYzYjYzMzE0ZmNlYjkxZiIsInJvbGUiOiJlZHVjYXRvciIsImlhdCI6MTc1MTEyNjA3MSwiZXhwIjoxNzUxMjEyNDcxfQ.7lL7Tw3LPLhnVBOj6zIBbliaD2rB-GE1-YVWZ2khXL8; Max-Age=604800; Path=/; Expires=Sat, 05 Jul 2025 15:54:31 GMT; HttpOnly; Secure; SameSite=None
Origin: http://localhost:5000
Content-Type: application/json


{"courseId": "686003dd18eecc134e89ee16"}